name: Build (ya make)
description: Build targets
inputs:
  build_target:
    required: false
    description: "build target"
  build_preset:
    required: true
    default: "relwithdebinfo"
    description: "relwithdebinfo, release-asan, release-tsan"
  bazel_remote_uri:
    required: false
    description: "bazel-remote endpoint"
  bazel_remote_username:
    required: false
    description: "bazel-remote username"
  bazel_remote_password:
    required: false
    description: "bazel-remote password"
  link_threads:
    required: false
    default: "8"
    description: "link threads count"

runs:
  using: "composite"
  steps:
    - name: Init
      id: init
      shell: bash
      run: |
        ping 127.0.0.1 -c 2

    - name: build
      id: build
      shell: bash
      run: |
        ping 127.0.0.1 -c 2

    - name: sync logs to s3
      if: always()
      shell: bash
      run: |
        echo "::group::s3-sync"
        ping 127.0.0.1 -c 20
        echo "::endgroup::"

    - name: comment-build-status
      shell: bash
      run: |
        ping 127.0.0.1 -c 2

    - name: show free space
      if: always()
      shell: bash
      run: df -h
