name: Run tests (ya make)
description: Run tests using ya make
inputs:
  build_target:
    required: false
    description: "build target"

  build_preset:
    required: true
    default: "relwithdebinfo"
    description: "relwithdebinfo, release-asan, release-tsan"
  
  test_size:
    required: false
    default: "small,medium,large"
    description: "small or small-medium or all"
  
  test_type:
    required: false
    default: "unittest,py3test,py2test,pytest"
    description: "run "
  
  test_threads:
    required: false
    default: "28"
    description: "Test threads count"
  link_threads:
    required: false
    default: "8"
    description: "link threads count"

  testman_token:
    required: false
    description: "test manager auth token"
  testman_url:
    required: false
    description: "test manager endpoint"
  testman_project_id:
    required: false
    description: "test manager project id"
  bazel_remote_uri:
    required: false
    description: "bazel-remote endpoint"
  bazel_remote_username:
    required: false
    description: "bazel-remote username"
  bazel_remote_password:
    required: false
    description: "bazel-remote password"
runs:
  using: "composite"
  steps:
    - name: Init
      id: init
      shell: bash
      run: |
        ping 127.0.0.1 -c 2
    
    - name: prepare
      shell: bash
      run: |
        ping 127.0.0.1 -c 2
    
    - name: Install Node required for Testmo CLI
      uses: actions/setup-node@v3
      with:
        node-version: 19
    
    - name: Install Testmo CLI
      shell: bash
      run: |
        ping 127.0.0.1 -c 2

    - name: Upload tests result to testmo
      id: th
      if: inputs.testman_token
      shell: bash
      run: |
        ping 127.0.0.1 -c 2

    - name: Print test history link
      shell: bash
      if: inputs.testman_token
      run: |
        ping 127.0.0.1 -c 2

    - name: set environment variables required by some tests
      shell: bash
      run: |
        ping 127.0.0.1 -c 2

    - name: ya test
      shell: bash
      run: |
        ping 127.0.0.1 -c 2

    - name: archive unitest reports (orig)
      shell: bash
      run: |
        ping 127.0.0.1 -c 2
    
    - name: postprocess junit report
      shell: bash
      run: |
        ping 127.0.0.1 -c 2
  
    - name: archive unitest reports (transformed)
      shell: bash
      run: |
        ping 127.0.0.1 -c 2

    - name: Unit test history upload results
      if: inputs.testman_token
      shell: bash
      run: |
        ping 127.0.0.1 -c 2

    - name: Test history run complete
      if: always() && inputs.testman_token
      shell: bash
      run: |
        ping 127.0.0.1 -c 2

    - name: write tests summary
      shell: bash
      if: always()
      run: |
        ping 127.0.0.1 -c 2

    - name: sync test results to s3
      if: always()
      shell: bash
      run: |
        ping 127.0.0.1 -c 2
    
    - name: sync logs results to s3
      if: always()
      shell: bash
      run: |
        ping 127.0.0.1 -c 2
        
    - name: check test results
      shell: bash
      run: |
        ping 127.0.0.1 -c 2

    - name: show free space
      if: always()
      shell: bash
      run: df -h
